AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - 'bin/**/*'
    - 'spec/**/*'
    - 'tmp/**/*'

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 10

Layout/IndentHash:
  EnforcedStyle: consistent

Style/BlockComments:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false
