AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - 'bin/**/*'
    - 'spec/**/*'
    - 'tmp/**/*'

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 15

Layout/IndentHash:
  EnforcedStyle: consistent

Style/BlockComments:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  Enabled: false

# Square brackets blocks are much faster
Style/SymbolProc:
  Enabled: false
